# Generated by Django 6.0.5 on 2026-05-19 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_review_updated_at_alter_review_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='review_count',
            field=models.IntegerField(default=0),
        ),
    ]
